-- Creación de la BD
CREATE DATABASE USIL_FUTBOL;
GO

-- Seleccionar la BD
USE USIL_FUTBOL;
GO

-- CREACION DE UNA TABLA

CREATE TABLE CAMPEONATO(
  ID_CAMP INT NOT NULL IDENTITY,
  ANIO    INT NOT NULL,
  NOMBRE  VARCHAR(150) NOT NULL,
  FEC_INICIO DATE NOT NULL,
  FEC_FIN DATE NOT NULL,
  CONSTRAINT PK_CAMPEONATO PRIMARY KEY( ID_CAMP ),
  CONSTRAINT U_ANIO UNIQUE( ANIO )
);
GO

INSERT INTO CAMPEONATO(ANIO,NOMBRE,FEC_INICIO,FEC_FIN)
VALUES(2014,'DESENTRALIZADO USIL 2014','20140105','20141215');

INSERT INTO CAMPEONATO(ANIO,NOMBRE,FEC_INICIO,FEC_FIN)
VALUES(2015,'DESENTRALIZADO EMPRENDEDORES 2015','20150205','20151215');

INSERT INTO CAMPEONATO(ANIO,NOMBRE,FEC_INICIO,FEC_FIN)
VALUES(2016,'DESENTRALIZADO CHICLAYO 2016','20160105','20161215');

SELECT * FROM CAMPEONATO;

-- =========================================
-- TABLA: EQUIPO
-- =========================================
CREATE TABLE EQUIPO(
  ID_EQUIPO INT NOT NULL IDENTITY,
  NOMBRE    VARCHAR(100) NOT NULL,
  CIUDAD    VARCHAR(40) NOT NULL,
  DIRECCION VARCHAR(100) NOT NULL,
  TELEFONO  VARCHAR(20) NOT NULL,
  CONSTRAINT PK_EQUIPO PRIMARY KEY (ID_EQUIPO),
  CONSTRAINT U_NOMBRE_EQUIPO UNIQUE (NOMBRE)
);

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS INMORTALES','CHICLAYO','AV. BALTA 456','074-23546');

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS CARA SUCIAS','LIMA','AV. CALE 1 NRO. 786','98345678');

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS LAGARTOS', 'AREQUIPA','AV. NO SE 823','7834562');

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS INTOCABLES','TRUJILLO','AV. LIMA 7623','783456872');
GO

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS INFORMATICOS', 'LIMA','AV. NAPO 7655','893245876');
GO

SELECT * FROM EQUIPO;
GO

-- ========================================
-- TABLA: PARTICIPA
-- =======================================

CREATE TABLE PARTICIPA(
  ID_CAMP INT NOT NULL,
  ID_EQUIPO INT NOT NULL,
  FEC_INS DATE NOT NULL,
  POSICION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_PARTICIPA PRIMARY KEY( ID_CAMP, ID_EQUIPO )
);
GO

-- campeonato 2014
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,1,'20140112');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,2,'20140113');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,3,'20140113');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,4,'20140115');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,5,'20140116');
GO

select * from participa;
go


SELECT * FROM CAMPEONATO;
SELECT * FROM EQUIPO;

















