-- Creación de la BD
CREATE DATABASE USIL_FUTBOL;
GO

-- Seleccionar la BD
USE USIL_FUTBOL;
GO

-- CREACION DE UNA TABLA

CREATE TABLE CAMPEONATO(
  ID_CAMP INT NOT NULL IDENTITY,
  ANIO    INT NOT NULL,
  NOMBRE  VARCHAR(150) NOT NULL,
  FEC_INICIO DATE NOT NULL,
  FEC_FIN DATE NOT NULL,
  CONSTRAINT PK_CAMPEONATO PRIMARY KEY( ID_CAMP ),
  CONSTRAINT U_ANIO UNIQUE( ANIO )
);
GO

INSERT INTO CAMPEONATO(ANIO,NOMBRE,FEC_INICIO,FEC_FIN)
VALUES(2014,'DESENTRALIZADO USIL 2014','20140105','20141215');

INSERT INTO CAMPEONATO(ANIO,NOMBRE,FEC_INICIO,FEC_FIN)
VALUES(2015,'DESENTRALIZADO EMPRENDEDORES 2015','20150205','20151215');

INSERT INTO CAMPEONATO(ANIO,NOMBRE,FEC_INICIO,FEC_FIN)
VALUES(2016,'DESENTRALIZADO CHICLAYO 2016','20160105','20161215');

SELECT * FROM CAMPEONATO;

-- =========================================
-- TABLA: EQUIPO
-- =========================================
CREATE TABLE EQUIPO(
  ID_EQUIPO INT NOT NULL IDENTITY,
  NOMBRE    VARCHAR(100) NOT NULL,
  CIUDAD    VARCHAR(40) NOT NULL,
  DIRECCION VARCHAR(100) NOT NULL,
  TELEFONO  VARCHAR(20) NOT NULL,
  CONSTRAINT PK_EQUIPO PRIMARY KEY (ID_EQUIPO),
  CONSTRAINT U_NOMBRE_EQUIPO UNIQUE (NOMBRE)
);

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS INMORTALES','CHICLAYO','AV. BALTA 456','074-23546');

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS CARA SUCIAS','LIMA','AV. CALE 1 NRO. 786','98345678');

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS LAGARTOS', 'AREQUIPA','AV. NO SE 823','7834562');

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS INTOCABLES','TRUJILLO','AV. LIMA 7623','783456872');
GO

INSERT INTO EQUIPO(NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES
('LOS INFORMATICOS', 'LIMA','AV. NAPO 7655','893245876');
GO

SELECT * FROM EQUIPO;
GO

-- ========================================
-- TABLA: PARTICIPA
-- =======================================

CREATE TABLE PARTICIPA(
  ID_CAMP INT NOT NULL,
  ID_EQUIPO INT NOT NULL,
  FEC_INS DATE NOT NULL,
  POSICION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_PARTICIPA PRIMARY KEY( ID_CAMP, ID_EQUIPO ),
  CONSTRAINT FK_PARTICIPA_EQUIPO
	FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO,
  CONSTRAINT FK_PARTICIPA_CAMPEONATO
	FOREIGN KEY(ID_CAMP) REFERENCES CAMPEONATO
);
GO

-- campeonato 2014
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,1,'20140112');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,2,'20140113');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,3,'20140113');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,4,'20140115');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(1,5,'20140116');
GO


-- campeonato 2015
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(2,1,'20150111');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(2,2,'20150118');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(2,3,'20150119');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(2,4,'20150119');
GO

-- campeonato 2016
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(3,2,'20150107');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(3,3,'20150110');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(3,4,'20150201');
INSERT INTO PARTICIPA(ID_CAMP,ID_EQUIPO,FEC_INS)
VALUES(3,5,'20150202');
GO

-- ====================================
-- TABLA: JUGADOR
-- ====================================
CREATE TABLE JUGADOR(
  ID_JUGADOR INT NOT NULL IDENTITY,
  NOMBRE VARCHAR(50) NOT NULL,
  TELEFONO VARCHAR(20) NULL,
  EMAIL VARCHAR(50) NULL,
  CONSTRAINT PK_JUGADOR PRIMARY KEY(ID_JUGADOR)
);
GO

-- DATOS DE JUGADORES
INSERT INTO JUGADOR(NOMBRE) VALUES('JULIO EL DIAMENTE URIBE');
INSERT INTO JUGADOR(NOMBRE) VALUES('TEOFILO EL NENE CUBILLAS');
INSERT INTO JUGADOR(NOMBRE) VALUES('JUAN CARLOS EL CIEGO OBLITAS');
INSERT INTO JUGADOR(NOMBRE) VALUES('RONALDINHO');
INSERT INTO JUGADOR(NOMBRE) VALUES('GUSTAVO CORONEL');
INSERT INTO JUGADOR(NOMBRE) VALUES('JULIO MELENDEZ');
INSERT INTO JUGADOR(NOMBRE) VALUES('HUGO EL CHOLO SOTIL');
INSERT INTO JUGADOR(NOMBRE) VALUES('JULIO PERICO LEON');
INSERT INTO JUGADOR(NOMBRE) VALUES('JUAN JOSE MUÑANTE');
INSERT INTO JUGADOR(NOMBRE) VALUES('ERNESTO LABARTE');
GO

-- ====================================
-- TABLA: JUEGA
-- ====================================
CREATE TABLE JUEGA(
  ID_CAMP INT NOT NULL,
  ID_EQUIPO INT NOT NULL,
  ID_JUGADOR INT NOT NULL,
  FEC_INS DATE NOT NULL,
  CONSTRAINT PK_JUEGA PRIMARY KEY(ID_CAMP,ID_EQUIPO,ID_JUGADOR),
  CONSTRAINT FK_JUEGA_PARTICIPA
	FOREIGN KEY(ID_CAMP,ID_EQUIPO) REFERENCES PARTICIPA,
  CONSTRAINT FK_JUEGA_JUGADOR
	FOREIGN KEY(ID_JUGADOR) REFERENCES JUGADOR
);
GO

-- jugadores del 2014
-- equipo 1
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,1,1,'20140202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,1,2,'20140202');
-- equipo 2
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,2,3,'20140202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,2,4,'20140202');
-- equipo 3
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,3,5,'20140202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,3,6,'20140202');
-- equipo 4
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,4,7,'20140202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,4,8,'20140202');
-- equipo 5
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,5,9,'20140202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(1,5,10,'20140202');


-- jugadores del 2015
-- equipo 1
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,1,2,'20150202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,1,3,'20150202');
-- equipo 2
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,2,1,'20150202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,2,4,'20150202');
-- equipo 3
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,3,7,'20150202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,3,6,'20150202');
-- equipo 4
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,4,5,'20150202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,4,8,'20150202');
-- equipo 5
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,5,9,'20150202');
INSERT INTO JUEGA(ID_CAMP,ID_EQUIPO,ID_JUGADOR,FEC_INS)
VALUES(2,5,100,'20150202');



SELECT * FROM JUEGA;
SELECT * FROM CAMPEONATO;
select * from participa;
go


SELECT * FROM CAMPEONATO;
SELECT * FROM EQUIPO;

















