pregunta 01
===========

Desarrollar un procedimiento que
permita actualizar la nota de un estudiantes en un curso.


pregunta 02
===========
Desarrollar un procedimiento que permita obtener un listado de los estudiantes matriculados en un curso con sus respectivas notas.


Debe mostrar el nombre completo de los estudiantes.

El listado debe ser en función al codigo
del curso programado.


pregunta 03
===========

Desarrollar un procedimiento que permita
matricular a un estudiante.


